config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  get '/about', to: 'sessions#about'
  get '/map', to: 'sessions#map'
  get '/goodbye', to: 'sessions#goodbye'
  resources :posts
  resources :users, except: [:index]
  post '/posts/query', to: 'posts#query', as: 'query'
  get '/users/:id/details', to: 'users#details', as: 'details'
  patch '/users/:id/details', to: 'users#updatedetails'
  get '/users/:id/posts', to: 'users#posts', as: 'user_posts'
  get '/users/:id/liked', to: 'users#liked', as: 'user_likes'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#logout'
  post '/likes', to: 'likes#create', as: 'like_post'
  delete '/likes', to: 'likes#destroy', as: 'unlike_post'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :location
  belongs_to :category
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  validates :title, :content, :location, presence: true

  scope :popular, -> {order('likes_count desc')}
  scope :newest, -> {order('created_at desc')}
  scope :find_by_category, lambda {|category_id| where(['category_id = ?', category_id]).limit(20)}
  scope :find_by_location, lambda {|location_id| where(['location_id = ?', location_id]).limit(20)}
  scope :find_since_date, lambda {|created_at| where(['created_at > ?', created_at]).limit(20)}
  
  @@finders = {
    'Since'=>:find_since_date,
    'Location'=>:find_by_location,
    'Category'=>:find_by_category,
  }
  @@sorters = {
    'Likes'=>:popular,
    'Newest'=>:newest
  }

  def self.check_dates
    d = DateTime.now
    [
      ["The Past Week", (d - 7)],
      ["The Past Two Weeks", (d - 14)],
      ["The Past Month", (d << 1)],
      ["The Past 3 Months", (d << 3)]
    ]
  end
  # Using named scopes stored in class vars above, takes arguments (find by some type, arg for that finder, sort method) and queries the db for those results.
  def self.record_builder(finder='Since', value=Date.today, sorter='Likes')
    Post.send(@@finders[finder], value).send(@@sorters[sorter])
  end

  def category_name=(category)
    self.category = Category.find_or_create_by(name: category)
  end

  def category_name
    self.category ? self.category.name : nil
  end

  def self.last_ten
    Post.all.order(created_at: :desc).limit(10)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :get_post, only: [:show, :edit, :update, :destroy]
    
    # Index primarily driven by navbar which sends query details to 'post<-HTTP verb query' located at bottom of the file then returns them to index in a flash and uses Post.record_builder (see post.rb for more explanation). Navigating straight to index will return today's posts sorted by like count.
    def index
        @params = flash[:query] ||= {}
        case @params.length
        when 0
            @header = "All Thanks" 
            @posts = Post.record_builder()
        when 1
            @finder = @params.keys.first
            @value = @params.values.first
            @finder_name = get_name(@finder, @value)
            @posts = Post.record_builder(@finder, @value)
        when 2
            @finder = @params.keys.first
            @value = @params.values.first
            @sorter = @params.keys.second
            @finder_name = get_name(@finder, @value)
            @posts = Post.record_builder(@finder, @value, @sorter)
        end
    end

    def new
        @post = Post.new
        @locations = Location.all
        @post.location = user_logged_in.location
        @errors = flash[:errors]
    end
    
    def create
        params[:post][:user_id] = user_logged_in.id
        post = Post.create(post_params)
        if post.valid?
            redirect_to post
        else
            flash[:errors] = post.errors.full_messages
            redirect_to new_post_path
        end
    end
    
    def show
    end
    
    def edit
        @locations = Location.all
        @errors = flash[:errors]
    end

    def update
        params[:post][:user_id] = user_logged_in.id
        post = @post.update(post_params)
        if post
            redirect_to @post
        else
            flash[:errors] = post.errors.full_messages
            redirect_to post_edit_path(@path)
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end


    def query
        flash[:query] = params[:query]
        redirect_to posts_path
    end

    private

    def get_name(finder, value)
        if finder == "Location"
            "in #{finder.constantize.find(value).state}"
        elsif finder == "Category"
            " in #{finder.constantize.find(value).name}"
        else
            "since #{value.to_datetime.strftime("%B %d, %Y")}"
        end
    end

    def get_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:user_id, :title, :content, :location_id, :category_name)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |p| %>
    <%= p.label :private, "Would you like this post to be:"%>
    <%= p.radio_button :private, false, checked: true %>
    <%= p.label :private_false, "Public" %>
    <%= p.radio_button :private, true %>
    <%= p.label :private_true, "Private" %><br><br>
    <%= p.label :title %>
    <%= p.text_field :title %><br><br>
    <%= p.label :content %>
    <%= p.text_area :content %><br><br>
    <%= p.label :location_id, "Location"%>
    <%= p.collection_select :location_id, locations, :id, :state %><br><br>
    <%= p.label :category_name, "Category"%>
    <%= p.text_field :category_name %>
    <%= p.submit "Submit Thanks!"%>
<% end %>

app/views/posts/_like.html.erb
<% if logged_in? %>
    <% if like %>
      <%= button_to "🙏", unlike_post_path, method: :delete, params: {"like[id]"=>post.id} %>
    <% else %>
      <%= button_to "🙏", like_post_path, params: {"like[post_id]"=>post.id} %>
    <% end %>
<% else %>
      <%= button_to "🙏", login_path %>
<% end %>

app/views/posts/_postnav.html.erb
<span id="index_nav">
    <span id="todays_thanks">
        <%= link_to "Today's Thanks", posts_path %>
    </span>
    <span id="date_select">
        <%= form_tag query_path do %>
            <%= label_tag "Thanks by: "%>
            <%= select_tag 'query[Since]', options_for_select(Post.check_dates), onchange: 'this.form.submit()', prompt: "Time Period" %>
        <% end %>
    </span>

    <span id="location_select">
        <%= form_tag query_path do %>
            <%= label_tag "Thanks by: "%>
            <%= select_tag 'query[Location]', options_from_collection_for_select(Location.all, :id, :state), onchange: 'this.form.submit()', prompt: "State" %>
        <% end %>
    </span>

    <span id="category_select">
        <%= form_tag query_path do %>
            <%= label_tag "Thanks by: "%>
            <%= select_tag 'query[Category]', options_from_collection_for_select(Category.all, :id, :name), onchange: 'this.form.submit()', prompt: "Category" %>
        <% end %>
    </span>
</span>

app/views/posts/by_user.html.erb
<% if user_logged_in == @user %>
    <h2>My Thanks</h2>
    <ul>
        <% @posts.each do |p| %>
            <li>
                <span><%= link_to p.title, post_path(p) %><br>
                <%= truncate(p.content, length: 75)%></span>
                <span id="likes_count"><%= "🙏 #{p.likes_count}" %></span>
            </li>
        <% end %>
    </ul>
<% else %>
    <p>You don't have permission to view this user's posts</p>
    <% link_to "Back to All Thanks", posts_path %>
<% end %>

app/views/posts/edit.html.erb
<h1>Amend Your Thanks</h1>
<%= render partial: 'shared/errors', locals: {errors: @errors} %>
<%= render partial: 'form', locals: {post: @post, user: @user, locations: @locations}%>

app/views/posts/index.html.erb
<div id="index_header">
    <%if @header %>
        <h2><%= @header %></h2>
    <% else %>
        <h2>Thanks <%= @finder_name %></h2>
    <% end %>
    <%= render 'postnav' %>
</div>
<div id="index_body">
<% if @posts.present? %>
    <ul>
        <% @posts.each do |post| %>
            <li>
                <%= render partial: 'shared/postpreview', locals: {post: post}%>
            </li>
        <% end %>
    </ul>
    <% else %>
        <p id="empty_error">Sorry, there are no thanks in <%= @finder_name %> </p>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>Give Thanks</h1>
<%= render partial: 'shared/errors', locals: {errors: @errors} %>
<%= render partial: 'form', locals: {post: @post, user: @user, locations: @locations}%>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<h3>By: <%= @post.user.username %></h3>
<p><%= @post.content %></p>
<%=%>
<span><h4>Tagged in:</h4> <%= button_to @post.category.name.capitalize, query_path, params: {"query[Category]"=>@post.category_id} %></span>
<span><h4>Tagged in:</h4> <%= button_to @post.location.state.capitalize, query_path, params: {"query[Location]"=>@post.location_id} %></span>

<%= render partial: "shared/like", locals: {post: @post, like: user_logged_in.liked_posts.include?(@post)} %>
<%= @post.likes_count%>
<%= link_to 'Edit Post', edit_post_path(@post) %>
<%= button_to "Delete Post", @post, method: :delete, class: "button" %>