config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  get '/about', to: 'sessions#about'
  get '/map', to: 'sessions#map'
  get '/goodbye', to: 'sessions#goodbye'
  resources :posts
  resources :users, except: [:index]
  post '/posts/query', to: 'posts#query', as: 'query'
  get '/users/:id/details', to: 'users#details', as: 'details'
  patch '/users/:id/details', to: 'users#updatedetails'
  get '/users/:id/posts', to: 'users#posts', as: 'user_posts'
  get '/users/:id/liked', to: 'users#liked', as: 'user_likes'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#logout'
  post '/likes', to: 'likes#create', as: 'like_post'
  delete '/likes', to: 'likes#destroy', as: 'unlike_post'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thankful-e</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="viewer" class="container-fluid">
    <div class="row">
      <div class="col-md-4 text-center">
        <div id="site_title"><h1> <%= link_to '🙏 Thankful-e', root_path %> </h1></div>
        <div id="nav">
          <ul>
            <li><%= link_to 'About Thankful-e', about_path %></li>
            <li><%= link_to 'Thanks Digest', posts_path %></li>
            <% if logged_in? %>
              <li><%= link_to "My Thanks", user_posts_path(user_logged_in.id) %></li>
              <li><%= link_to "Give Thanks", new_post_path %></li>
              <li><%= link_to "Thanks I've 🙏", user_likes_path(user_logged_in.id) %></li>
              <li><%= link_to 'My Account', user_path(user_logged_in.id) %></li>
            <% else %>
              <li><%= link_to 'Give Thanks', new_user_path %></li>
            <% end %>
          </ul>
        </div>
        <div id="activity">
          <%= render partial: 'shared/activity', locals: {posts: last_ten_posts} %>
        </div>
      </div>
      <div class="col-md-8">
        <span class="user_greeting_logout">
          <% if !logged_in? %> 
              <%= link_to 'Log In', login_path %>
              <%= link_to 'Sign Up', new_user_path, class: "button"%>
            <% else %> 
              <%= link_to "Hi, #{user_logged_in.username}!", user_path(user_logged_in) %>
              <%= button_to "Log Off", logout_path, class: "button" %>
            <% end %>
        </span>
        <div id="main">
        <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>